name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m ensurepip --upgrade
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run Flask app (for testing)
      run: |
        export FLASK_APP=app.py
        export FLASK_ENV=development
        flask run --host=0.0.0.0 --port=5000 &
        sleep 5
        curl http://127.0.0.1:5000

